GET http://localhost:3000/vehicles

###
GET http://localhost:3000/vehicles/6494e3ae7ddbe1c7bc2ed064

###
POST http://localhost:3000/vehicles
Accept: application/json
Content-Type: application/json

{
  "name": "Bob Frong",
  "age": 29,
  "city": "Boston",
  "country": "USA",

  ""
}
